---

- name: Install firewalld
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - firewalld
      - python3-firewall

- name: Close public services
  ansible.builtin.command: firewall-cmd --permanent --remove-service ssh --zone=external
  notify:
    - firewall-cmd-reload

- include_tasks: firewall.yml

